### ISSUE TITLE
opcode versioning

### ISSUE THREAD

**Issue by Every-L** [neowutran/TeraDpsMeterData#15]
Hi, I am very noob and interested in programming. I was wondering how you version the opcode. Is it just a bogus value that you put in each patch? So as long as it contains same opcode, would the DpsMeter still be functional with the name of 111111.txt and smt_111111.txt?

**Comment by Gl0** [comment]
It has different mapping for each version. If client use unknown version - meter can't work.

**Comment by Every-L** [comment]
I got the opcode with the scanner, so I am just wondering if the name of the file matters the functionality of the meter. For instance, if there are two exact same file one with named "313623.txt(created by meter update)" and "111111.txt(generated from my computer)", would 111111.txt work just same as 313623.txt without the name change?

**Comment by Gl0** [comment]
no. meter use client version as part of filename when loading opcodes

**Comment by Every-L** [comment]
Thanks for reply. My last question, how do I fetch the client version?

**Comment by Gl0** [comment]
https://github.com/neowutran/TeraDpsMeterData/blob/master/copypaste-tuto/Gl0-dll.txt

**Comment by Every-L** [comment]
Thanks a lot
