### ISSUE TITLE
OPCODE [question]

### ISSUE THREAD

**Issue by angelgun1** [neowutran/TeraDpsMeterData#5]
Before i'm KTERA user and english is very poor ... plz understand.

I've read some CE instructions, and also read your link.

In KTERA, i cant open process because of XIGNCODE (just my think.)

it's not only CE but 'Extreme Injector v3' too.

How can i find OPCODE ?

**Comment by neowutran** [comment]
You need the freeze the xigncode3 process. 
- Launch the game
- A popup appear with a progress bar for xigncode3
- When the progressbar is at ~30%, freeze xigncode3
- Do what you want. 

And for extreme injector v3, don't freeze the process. Just launch extreme injector, when the progressbar is at ~30% inject what you want & profit

(here is a small piece of code to freeze xigncode3
https://github.com/neowutran/Freezer
)

**Comment by angelgun1** [comment]
thanks i will try :)

**Comment by angelgun1** [comment]
It's late but thank your advice and I can success extract opcode by this advice.
